# Generated by Django 4.1.5 on 2023-02-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ngoapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ngo",
            name="ngotwitter",
            field=models.TextField(blank=True),
        ),
    ]
