# Generated by Django 4.1.5 on 2023-02-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ngoapp", "0002_ngo_ngotwitter"),
    ]

    operations = [
        migrations.AddField(
            model_name="ngo",
            name="ngostate",
            field=models.TextField(blank=True),
        ),
    ]
