# Generated by Django 4.1.5 on 2023-02-11 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ngoapp", "0003_ngo_ngostate"),
    ]

    operations = [
        migrations.CreateModel(
            name="userpro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userid", models.TextField()),
                ("userbio", models.TextField(blank=True)),
                ("firstname", models.TextField(blank=True)),
                ("lastname", models.TextField(blank=True)),
                ("password", models.TextField(blank=True)),
                ("kindofngo", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
