# Generated by Django 4.1.5 on 2023-02-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ngoapp", "0005_ngo_ngofield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpro",
            name="userid",
            field=models.TextField(blank=True),
        ),
    ]
