# Generated by Django 4.1.5 on 2023-02-11 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ngoapp", "0006_alter_userpro_userid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userpro",
            name="user",
        ),
    ]
