# Generated by Django 4.1.5 on 2023-02-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ngoapp", "0007_remove_userpro_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="ngo",
            name="ngonm",
            field=models.TextField(blank=True),
        ),
    ]
