# Generated by Django 4.1.5 on 2023-02-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ngoapp", "0008_ngo_ngonm"),
    ]

    operations = [
        migrations.CreateModel(
            name="ngoorder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ngoreg", models.TextField(blank=True)),
                ("ngocat", models.TextField(blank=True)),
                ("ngoexp", models.TextField(blank=True)),
                ("ngoamount", models.TextField(blank=True)),
            ],
        ),
    ]
